dist: focal

jobs:
  include:
  - name: Enterprise 1.3.0.x
    env: KONG_VERSION=1.3.0.x
  - name: Enterprise 1.5.0.x
    env: KONG_VERSION=1.5.0.x
  - name: Enterprise 2.4.1.x
    env: KONG_VERSION=2.4.1.x
  - name: Kong CE 2.4.x
    env: KONG_VERSION=2.4.x
  - name: Nightly EE-master
    env: KONG_VERSION=nightly-ee POSTGRES=latest CASSANDRA=latest
  #- name: Nightly CE-master
  #  env: KONG_VERSION=nightly POSTGRES=latest CASSANDRA=latest

install:
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"

script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"

notifications:
  slack:
    if: branch = master AND type != pull_request
    on_success: change
    on_failure: always
    rooms:
      secure: Y0B50ZsYzGoxVLSbyBota1YXKkrxnPsHcAQxS+Z6SiFcirm2U0YlBFs979jHaujMi9eCuDgd2go9DNLbqqYqs7pJsusuR60sQfrwO4N8oR6qTLCM2DWltSkvwX6pzZEN/xMQWvbRoUrPQXYvA+f0jlfHt6Zp91ZcKiQUqcoO3HWEruXDK+l+0Ej9sIiQkEf53KFmKJl5TSWFm4oGlKDy3fv9nxNxQaHnxxoC9p0xdTOcwEg6Iiwrc/gVyGG9uhalQyw/fu33z2eUsRot1DY5jUqHKvGgWEV+Ui0hphDeY7XQDdmgnzjqwFdewHYgiMyzVtxXYzKCtnIM9iLOAb0Df3fiKb9veEWjIeZ2Px9PQqMPD1lMFHtiIY/W1X48kAnLcDt8AuYNF8udsL+1jiGFW6JPx1DZwIS4VAZa6D5IaZ6GT6bUcvVb0eqik6LugQI1ZJTLcOmgsNBRX7JwOXxv9nyPbI+owqwgqz3KRAxPEiG5lM+0K4wXNr3O1GXr4JoAyqaapSee1ePLE+L7b57wKc1Yu9TmsJvhHmHlmgDtOOeFzhhnQIbZ/XYCtW0tztytBd1iTOKjaOK5feOR8IZDB0dmuvrNnSIaTt/twZH+BcYUU7I1ULp31bbMjH+kkPnLzUrdmfLqSVjOu40sFSyme1uZjXalK5x071TAxmd+n5Q=
